# public/imageConfig.yaml
images:
  - src: /denmark.png
    alt: Denmark Bollard
    name: Denmark
    continent: Europe
    colors:
      - red
      - yellow
      - white
  - src: /italy-front-1.png
    alt: Italy Front
    name: Italy Front
    continent: Europe
    colors: 
      - red
      - black
      - gray
  - src: /italy-back-1.png
    alt: Italy Back
    name: Italy Back
    continent: Europe
    colors: 
      - black
      - white
      - gray
  - src: /britain.jpg
    alt: Britain
    name: britain
    continent: Europe
    colors:
      - red
      - white
      - blue
  - src: /germany.jpg
    alt: Germany
    name: germany
    continent: Europe
    colors:
      - black
      - red
      - yellow
  - src: /poland.jpg
    alt: Poland
    name: poland
    colors:
      - white
      - red
  - src: /croatia.jpg
    alt: Croatia
    name: croatia
    colors:
      - red
      - white
      - blue