# public/imageConfig.yaml
images:
  - src: /denmark.png
    alt: Denmark Bollard
    name: Denmark
    continent: Europe
    colors:
      - red
      - yellow
      - white
    side:
      - front
  - src: /denmark-back-1.png
    alt: Denmark Bollard
    name: Denmark
    continent: Europe
    colors:
      - red
      - white
    side:
      - back
  - src: /italy-front-1.png
    alt: Italy Front
    name: Italy Front
    continent: Europe
    colors: 
      - red
      - black
      - gray
    side:
      - front
  - src: /italy-back-1.png
    alt: Italy Back
    name: Italy Back
    continent: Europe
    colors: 
      - black
      - white
      - gray
    side:
      - back
  - src: /australia-front-1.png
    alt: Australia Front
    name: Australia Front
    continent: Oceania
    colors: 
      - red
      - white
    side:
      - front
  - src: /australia-back-1.png
    alt: Australia Back
    name: Australia Back
    continent: Oceania
    colors:
      - white
      - gray
    side:
      - back

  - src: /spain-front-1.png
    alt: Spain Front
    name: Spain Front
    continent: Europe
    colors: 
      - yellow
      - white
      - black
    side:
      - front
  - src: /spain-back-1.png
    alt: Spain Back
    name: Spain Back
    continent: Europe
    colors:
      - white
      - black
    side:
      - back
